version: "3.8"
services:
  mysql:
    extends:
      file: docker-compose-prod.yml
      service: mysql
  rabbitmq:
    extends:
      file: docker-compose-prod.yml
      service: rabbitmq
    ports:
      - "${RABBITMQ_ADMIN_PORT:-15672}:15672"
  backend:
    extends:
      file: docker-compose-prod.yml
      service: backend
    ports:
      - "${BACKEND_PORT:-8082}:8082"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  frontend:
    extends:
      file: docker-compose-prod.yml
      service: frontend
    depends_on:
      backend:
        condition: service_healthy

networks:
  my-shared-network: {}

volumes:
  mysql-data: {}